apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  namespace: argocd
data:
  url: https://argocd.192.168.56.10.nip.io:32198/

  dex.config: |
    connectors:
      - type: github
        id: github
        name: Github
        config:
          clientID: <client_id>
          clientSecret: <client_secret>
          loadAllGroups: true