apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-configmap
  labels:
    app.kubernetes.io/name: argocd-rbac-configmap
    app.kubernetes.io/part-of: argocd
  namespace: argocd
data:
  policy.csv: |
    p, role:developer, applications, *, */*, allow
    g, role:developer, role:readonly

    g, paulokinjo, role:developer

  scopes: '[groups, preferred_username]'