apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-server
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  soruce:
    path: ./k8s
    repoURL: https://github.com/paulokinjo/prometheus
  