apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - argocd-application-prometheus.yaml  
  - argocd-application-prometheus-node-exporter.yaml
  - argocd-application-prometheus-alertmanager.yaml
  - argocd-application-grafana.yaml  
  # - sealed-secrets-controller.yaml

patches:
  # - target:
  #     version: v1
  #     kind: ConfigMap
  #     name: argocd-cm
  #   path: argocd-cm.yaml
  # - target:
  #     version: v1
  #     kind: ConfigMap
  #     name: argocd-rbac-cm
  #   path: argocd-rbac-cm.yaml
  - target:
      version: v1
      kind: Service
      name: argocd-server
    path: argocd-server.yaml
