apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- argocd-configmap.yaml
- argocd-rbac-configmap.yaml

patchesStrategicMerge:
- argocd-configmap.yaml
- argocd-server.yaml
- argocd-rbac-configmap.yaml