apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter-service
  labels:
    app: mongodb-exporter
spec:
  ports:
  - name: metrics
    port: 9216
    protocol: TCP
    targetPort: 9216
    nodePort: 32003
  selector:
    app: mongodb-exporter
  type: NodePort
status:
  loadBalancer: {}
