apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  storageClassName: "hostpath"
  claimRef:
    name: host-pvc
    namespace: default
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath: 
    path: /Users/paulo.kinjo/Documents/personal/kubernetes/statefull/lab2
    type: Directory


    