# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  config.vm.define "control" do |control|
    control.vm.box = "bento/ubuntu-20.04"
    control.vm.hostname = "control"
    control.vm.network "private_network", ip: "192.168.56.9"
    control.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    control.vm.provider "virtualbox" do |v|
      v.name = "control"
      v.gui = true
      v.memory = 2048
      v.cpus = 2      
      v.customize [
        "modifyvm", :id,
        "--vram", "32",
        "--graphicscontroller", "vmsvga",
        "--accelerate3d", "off",
        "--vrde",  "off",
        "--clipboard", "bidirectional",
      ]
    end
    control.vm.provision "shell", path: "bootstrap_desktop.sh"
  end  
end
