# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.define "docker" do |docker|
    docker.vm.box = "bento/ubuntu-20.04"
    docker.vm.hostname = "docker"
    docker.vm.network "private_network", ip: "192.168.56.20"
    docker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    docker.vm.provider "virtualbox" do |v|
      v.name = "docker"
      v.gui = false
      v.memory = 4096
      v.cpus = 2      
    end
  end  

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/focal64"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.10"
    # master.vm.network :public_network, type: "dhcp"     
    master.vm.provider "virtualbox" do |v|
      v.name = "master"
      v.memory = 2048
      v.cpus = 2      
    end
    master.vm.provision "shell", path: "bootstrap_master.sh"
  end

  config.vm.define "control" do |control|
    control.vm.box = "bento/ubuntu-20.04"
    control.vm.hostname = "control"
    control.vm.network "private_network", ip: "192.168.56.9"
    control.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    control.vm.provider "virtualbox" do |v|
      v.name = "control"
      v.gui = true
      v.memory = 2048
      v.cpus = 2      
      v.customize [
        "modifyvm", :id,
        "--vram", "32",
        "--graphicscontroller", "vmsvga",
        "--accelerate3d", "off",
        "--vrde",  "off",
        "--clipboard", "bidirectional",
      ]
    end
    control.vm.provision "shell", path: "bootstrap_desktop.sh"
  end  

  NodeCount = 3

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "worker#{i}" do |workernode|
      workernode.vm.box = "ubuntu/focal64"
      workernode.vm.hostname = "worker#{i}"
      workernode.vm.network "private_network", ip: "192.168.56.1#{i}"      
      # workernode.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)" 
      workernode.vm.provider "virtualbox" do |v|
        v.name = "worker#{i}"
        v.memory = 2048
        v.cpus = 2        
      end
    end
  end
end
