apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: fast-disk
      persistentVolumeClaim:
        claimName: pvc0
  containers:
    - name: ml-processer
      image: ml-processer-image
      volumeMounts:
        - mountPath: /var/lib/db
          name: fast-disk