apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io2
  iopsPerGB: "17"
  fsType: ext4