apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  volumes:
    - name: foo
      secret:
        secretName: login-credentials
  containers:
    - name: mycontainer
      image: redis
      volumeMounts:
        - mountPath: /etc/foo
          name: foo
          readOnly: true
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
