apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
        - name: master
          image: "docker.io/redis:6.0.5"
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          volumeMounts:
            - name: config
              mountPath: /redis-master
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
      volumes:
        - name: config
          configMap:
            name: redis-config
            items:
              - key: redis-config
                path: redis.conf
