config:
  guestbook_name: "MyPopRock Festival 2.0"
  backend_uri: "http://backend.cluster.local:30131/guestbook"
replicaCount: 1
image:
  repository: phico/frontend
  tag: "2.0"
service:
  port: 80
  type: NodePort
ingress:
  host: frontend.cluster.local
