apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoUrl: https://github.com/paulokinjo/kubernetes
    targetRevision: HEAD
    path: argo/nana-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: demoapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true