# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

NUMBER_OF_NODES = ENV['NODES'] || 2
MASTER_MEM = ENV['MEM'] || 2048
MASTER_CPUS = ENV['CPUS'] || 2
NODES_MEM = ENV['MEM'] || 3000
NODES_CPUS = ENV['CPUS'] || 1

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "scripts/common.sh"
  config.vbguest.auto_update = false
  # Kubernetes Master Server
  config.vm.define "kmaster" do |node|
    node.vm.box                           = "generic/ubuntu2004"
    node.vm.box_check_update              = false
    node.vm.box_version                   = "3.3.0"
    node.vm.hostname                      = "kmaster.example.com"
    node.vm.network "private_network", ip: "172.16.16.100"
    node.vm.provider :libvirt do |v|
      v.name    = "kmaster"
      v.memory  = MASTER_MEM
      v.cpus    = MASTER_CPUS
    end
    node.vm.provision "shell", path: "scripts/master.sh"
  end


  # Kubernetes Worker Nodes
  NodeCount = NUMBER_OF_NODES

  (1..NodeCount).each do |i|

    config.vm.define "kworker#{i}" do |node|

      node.vm.box               = "generic/ubuntu2004"
      node.vm.box_check_update  = false
      node.vm.box_version       = "3.3.0"
      node.vm.hostname          = "kworker#{i}.example.com"

      node.vm.network "private_network", ip: "172.16.16.10#{i}"

      node.vm.provider :libvirt do |v|
        v.name    = "kworker#{i}"
        v.memory  = NODES_MEM
        v.cpus    = NODES_CPUS
      end
      node.vm.provision "shell", path: "scripts/node.sh"
    end
  end
end
