apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.56.100-192.168.56.125
    - name: subnet-126
      protocol: layer2
      addresses:
      - 192.168.56.126-192.168.56.150