apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-frontend
  name: nginx-frontend-lb2
  annotations:
    metallb.universe.tf/address-pool: subnet-126
spec:
  selector:
    run: nginx-frontend
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  type: LoadBalancer
