# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  config.vm.define "docker" do |docker|
    docker.vm.box = "bento/ubuntu-20.04"
    docker.vm.hostname = "docker"
    docker.vm.network "private_network", ip: "192.168.56.20"
    docker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    docker.vm.provider "virtualbox" do |v|
      v.name = "docker"
      v.gui = false
      v.memory = 4096
      v.cpus = 2      
    end
  end  
end
